AuthenticationConfiguration:
  AccessSecretKey: "tM+Lm9iti8KzwHNeHXVzQrIcMm8GNIFjf73UiZpKnP4="
EnvironmentVariables:
  Environment: "development"
Server:
  Type: "tcp"
  Port: ":9000"
Logs:
  Path: ""
  Level: info
  MaxAge: 1
  MaxBackups: 4

